---
# tasks file for ansible-role-rrsync
#
## Both
- name: Install rsync
  package: 
    name: rsync
    state: installed

## Server
- name: symlink rrsync script to /usr/local/bin on RHEL7 derivatives
  file: 
    src: /usr/share/doc/rsync-3.0.9/support/rrsync 
    dest: /usr/local/bin/rrsync 
    owner: root 
    group: root 
    state: link 
    mode: 0755 
    follow: yes
  when: 
    - ansible_os_family == "RedHat" 
    - ansible_distribution_major_version == "7" 
    - rrsync_server

- name: symlink rrsync script to /usr/local/bin on RHEL6 derivatives
  file: 
    src: /usr/share/doc/rsync-3.0.6/support/rrsync 
    dest: /usr/local/bin/rrsync 
    owner: root 
    group: root 
    state: link 
    mode: 0755 
    follow: yes
  when: 
    - ansible_os_family == "RedHat" 
    - ansible_distribution_major_version == "6" 
    - rrsync_server

- name: on debian gunzip the rsync
  unarchive: src=/usr/share/doc/rsync/scripts/rrsync.gz dest=/usr/local/bin copy=no mode=0755
  when: ansible_os_family == "Debian" and rrsync_server

- name: create rrsync directory
  file: path={{ rsync_server_directory }} state=directory
        mode=0755
        owner={{ rrsync_cron_user }}
  when: rrsync_server and rrsync_server_create_directory != False

## Client
- name: Copy in private key
  copy: src="{{ rrsync_private_key }}"
        dest="/home/{{ rrsync_cron_user }}/.ssh/"
        owner="{{ rrsync_cron_user }}"
        mode=0600
  when: 
    - rrsync_cron_user is defined 
    - rrsync_client

- name: ensure rrsync_hosts are known hosts RSA
  lineinfile:
    dest: /home/{{ rrsync_cron_user }}/.ssh/known_hosts
    create: yes
    state: present
    line: "{{ lookup('pipe', 'ssh-keyscan -T 1 -t rsa ' + item) }}"
  with_items: "{{ rrsync_hosts }}"
  when: 
    - rrsync_hosts.0 != "" 
    - rrsync_client 
    - rrsync_known_hosts_rsa

- name: ensure rrsync_hosts are known hosts ECDSA
  lineinfile:
    dest: /home/{{ rrsync_cron_user }}/.ssh/known_hosts
    create: yes
    state: present
    line: "{{ lookup('pipe', 'ssh-keyscan -T 1 -t ecdsa ' + item) }}"
  with_items: "{{ rrsync_hosts }}"
  when: 
    - rrsync_hosts.0 != "" 
    - rrsync_client 
    - rrsync_known_hosts_ecdsa

- name: Set ownership
  file: path="/home/{{ rrsync_cron_user }}/.ssh/"
        owner="{{ rrsync_cron_user }}"
        state=directory
        recurse=yes
  when: rrsync_cron_user is defined and rrsync_client

- name: Set permission on .ssh
  file: path="/home/{{ rrsync_cron_user }}/.ssh/"
        owner="{{ rrsync_cron_user }}"
        state=directory
        mode=0700
  when: rrsync_cron_user is defined and rrsync_client

- name: Add rsync cronjobs
  cron:
    name: "{{ item.name }}"
    minute: "{{ item.minute }}"
    hour: "{{ item.hour }}"
    day: "{{ item.day|default(omit) }}"
    month: "{{ item.month|default(omit) }}"
    weekday: "{{ item.weekday|default(omit) }}"
    user: "{{ item.user }}"
    job: "{{ item.job }}"
    cron_file: "{{ item.name }}"
    state: "{{ item.state|default(omit) }}"
  with_items: "{{ rrsync_commands }}"
  when: rrsync_commands.0.job != "" and rrsync_client
